SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
GRAVITY = 0.8
GROUND_LEVEL = 780
FPS = 60
GAME_TITLE = "Super Mario Remake"
PLAYING = "playing"
MENU = "menu"
QUIT = "quit"
PAUSED = "paused"
GAME_OVER = "game_over"
RESTART = "restart"
QUIT_TO_MAIN_MENU = "quit_to_main_menu"